[tool.isort]
line_length = 79
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
known_third_party = ["djangorestframework", "flask"]  # Добавьте другие сторонние библиотеки, если нужно
known_first_party = ["notes"]  # Укажите ваш проект или модули